sudo: required
services:
  - docker

before_install:
  - docker build -t agmothilal/docker-react -f Dockerfile.dev .

script:
  - docker run agmothilal/docker-react npm run test -- --coverage

install: travis_wait 30 mvn install